ecss::Registry
friend class ArraysView
friend class Registry
std::conditional_t<ThreadSafe, std::shared_mutex, Dummy> ecss::Registry< ThreadSafe, Allocator >::componentsArrayMapMutex
Protects component arrays map/list (ThreadSafe build).
std::vector<Memory::SectorsArray<ThreadSafe, Allocator>*> ecss::Registry< ThreadSafe, Allocator >::mComponentsArrays
Flat list of all unique sectors arrays for iteration/maintenance.
std::vector<Memory::SectorsArray<ThreadSafe, Allocator>*> ecss::Registry< ThreadSafe, Allocator >::mComponentsArraysMap
Mapping: component type id -> sectors array (may group several component types).
Ranges<EntityId> ecss::Registry< ThreadSafe, Allocator >::mEntities
Dense range-managed entity id storage.
std::conditional_t<ThreadSafe, std::shared_mutex, Dummy> ecss::Registry< ThreadSafe, Allocator >::mEntitiesMutex
Protects entities container (ThreadSafe build).
Memory::ReflectionHelper ecss::Registry< ThreadSafe, Allocator >::mReflectionHelper
Type id / layout reflection helper.
FORCE_INLINE T * ecss::Registry< ThreadSafe, Allocator >::addComponent(EntityId entity, Args &&... args) noexcept
Add or overwrite a component T for an entity.
T Component type. Args Constructor argument types for T. entity Entity id (also used logically as sector id). args Construction / assignment arguments. Pointer to the stored component. Overwrites existing component instance (destructive assign semantics inside sector).
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
void ecss::Registry< ThreadSafe, Allocator >::addComponents(Func &&func)
Bulk add components via generator functor under a single write lock (thread-safe build).
T Component type. Func Callable returning std::pair<EntityId,T>. Return {INVALID_ID, {}} to stop. func Generator invoked repeatedly while lock is held. Optimizes many insertions by avoiding enter/leave lock per element.
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
void ecss::Registry< ThreadSafe, Allocator >::clear() noexcept
Clear all component arrays and remove all entities.
Does not shrink capacity. contains(id)==false for any previously allocated entity.
ECSType ecss::Registry< ThreadSafe, Allocator >::componentTypeId() const noexcept
Get a stable numeric type id for component T in this registry instance.
T Component type. Integral id (dense, zero-based). IDs may differ between different registry template instantiations.
Referenced by ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
FORCE_INLINE bool ecss::Registry< ThreadSafe, Allocator >::contains(EntityId entityId) const noexcept
True if registry currently owns entityId.
Referenced by ecss::Registry< ThreadSafe, Allocator >::destroyEntity.
void ecss::Registry< ThreadSafe, Allocator >::defragment() noexcept
Defragment all arrays (compacts fragmented dead slots).
Can be expensive if many arrays large – schedule during low frame-load moments.
FORCE_INLINE void ecss::Registry< ThreadSafe, Allocator >::defragment() noexcept
Defragment the container for component T (if it exists).
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
void ecss::Registry< ThreadSafe, Allocator >::destroyComponent(EntityId entity) noexcept
Destroy component T for a single entity (does nothing if not present).
T Component type. entity Entity id. @complexity O(1).
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
void ecss::Registry< ThreadSafe, Allocator >::destroyComponent(std::vector< EntityId > &entities) noexcept
Destroy component T for a batch of entities.
T Component type. entities Entity id list (will be sorted and truncated to valid sector capacity). Modifies the input vector (sorting, trimming out-of-range ids). Pins are waited if thread-safe; call outside tight critical paths if possible.
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
void ecss::Registry< ThreadSafe, Allocator >::destroyEntities(std::vector< EntityId > &entities) noexcept
Destroy a batch of entities and all their components (sequential per-array).
entities List of entities (not modified). Safe to call while other threads query (ThreadSafe=true). No parallelization here to avoid thread lifetime complexity.
References ecss::Memory::Sector::destroySector.
void ecss::Registry< ThreadSafe, Allocator >::destroyEntity(EntityId entityId) noexcept
Destroy a single entity and all of its components.
entityId Entity to remove (ignored if not owned). @complexity O(A) with A = number of component arrays.
References ecss::Registry< ThreadSafe, Allocator >::contains.
void ecss::Registry< ThreadSafe, Allocator >::forEachAsync(const std::vector< EntityId > &entities, Func &&func) noexcept
Apply a function to each entity in a list, pinning requested component types (thread-safe build).
Components Component types to pin. Func Callable signature: void(EntityId, Components*...). entities Entity ids to process. func Function invoked per entity. Skips entities missing any main pinned component (pointer passed may be nullptr for non-main).
FORCE_INLINE std::vector< EntityId > ecss::Registry< ThreadSafe, Allocator >::getAllEntities() const noexcept
Snapshot all entity ids (copy).
Memory::SectorsArray< ThreadSafe, Allocator > * ecss::Registry< ThreadSafe, Allocator >::getComponentContainer() noexcept
Get (or lazily create) the sectors container for component T.
T Component type. Pointer to container holding (possibly grouped) T. Will implicitly register a single-type array if not pre-registered.
References ecss::Registry< ThreadSafe, Allocator >::componentTypeId, ecss::Registry< ThreadSafe, Allocator >::getComponentContainer, ecss::Registry< ThreadSafe, Allocator >::registerArray.
Referenced by ecss::Registry< ThreadSafe, Allocator >::addComponent, ecss::Registry< ThreadSafe, Allocator >::addComponents, ecss::Registry< ThreadSafe, Allocator >::defragment, ecss::Registry< ThreadSafe, Allocator >::destroyComponent, ecss::Registry< ThreadSafe, Allocator >::destroyComponent, ecss::Registry< ThreadSafe, Allocator >::getComponentContainer, ecss::Registry< ThreadSafe, Allocator >::hasComponent, ecss::Registry< ThreadSafe, Allocator >::insert, ecss::Registry< ThreadSafe, Allocator >::insert, ecss::Registry< ThreadSafe, Allocator >::pinComponent, ecss::Registry< ThreadSafe, Allocator >::reserve, ecss::Registry< ThreadSafe, Allocator >::setDefragmentThreshold.
bool ecss::Registry< ThreadSafe, Allocator >::hasComponent(EntityId entity) noexcept
Check if an entity has a live component T.
T Component type. entity Entity id. True if the component exists and is alive; false otherwise. @complexity O(1). @thread_safety Locking/pinning applied if ThreadSafe=true.
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
FORCE_INLINE void ecss::Registry< ThreadSafe, Allocator >::insert(const Memory::SectorsArray< TS, Alloc > &array) noexcept
Copy-in an externally built sectors array for component T.
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
FORCE_INLINE void ecss::Registry< ThreadSafe, Allocator >::insert(Memory::SectorsArray< TS, Alloc > &&array) noexcept
Move-in an externally built sectors array for component T.
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
Registry & ecss::Registry< ThreadSafe, Allocator >::operator=(const Registry &other) noexcept=delete
Registry & ecss::Registry< ThreadSafe, Allocator >::operator=(Registry &&other) noexcept=delete
PinnedComponent< T > ecss::Registry< ThreadSafe, Allocator >::pinComponent(EntityId entity) noexcept
Pin component T for an entity (thread-safe build only).
T Component type. entity Entity id. PinnedComponent<T> (empty if component missing). The returned object must not outlive concurrent modification epochs.
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer, ecss::Memory::Sector::getComponentFromSector.
void ecss::Registry< ThreadSafe, Allocator >::registerArray(uint32_t capacity=0, Allocator allocator={}) noexcept
Explicitly register (group) component types into a shared sectors array.
ComponentTypes Component types to co-locate. capacity Initial reserve (optional). allocator Allocator instance to move. All types must either all be new or already co-grouped; partial mixes assert. Call before first implicit access to any of the grouped types.
Referenced by ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
ecss::Registry< ThreadSafe, Allocator >::Registry() noexcept=default
Default construct an empty registry (no arrays allocated until first use).
ecss::Registry< ThreadSafe, Allocator >::Registry(const Registry &other) noexcept=delete
ecss::Registry< ThreadSafe, Allocator >::Registry(Registry &&other) noexcept=delete
FORCE_INLINE void ecss::Registry< ThreadSafe, Allocator >::reserve(uint32_t newCapacity) noexcept
Reserve capacity (in sectors array units) for each listed component type.
Components Component types to reserve for. newCapacity Target capacity (implementation may round up).
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
FORCE_INLINE void ecss::Registry< ThreadSafe, Allocator >::setDefragmentThreshold(float threshold)
Set defragment threshold for component T container.
References ecss::Registry< ThreadSafe, Allocator >::getComponentContainer.
FORCE_INLINE EntityId ecss::Registry< ThreadSafe, Allocator >::takeEntity() noexcept
Allocate (take) a new entity id.
void ecss::Registry< ThreadSafe, Allocator >::update(bool withDefragment=true) noexcept
Maintenance pass (thread-safe build): process deferred erases and optionally defragment.
withDefragment If true, arrays that exceed thresholds may compact themselves. Recommended to call once per frame at a stable synchronization point. @thread_safety Internally synchronized.
void ecss::Registry< ThreadSafe, Allocator >::update(bool withDefragment=true) noexcept
Maintenance pass (non-thread-safe build): optionally defragment arrays immediately.
withDefragment If true, compacts arrays that request it. @thread_safety Caller must ensure exclusive access.
FORCE_INLINE auto ecss::Registry< ThreadSafe, Allocator >::view() noexcept
Create a full-range iterable view over all entities with the main component.
Components Component types to access; first drives iteration. ArraysView instance (full range).
FORCE_INLINE auto ecss::Registry< ThreadSafe, Allocator >::view(const Ranges< EntityId > &ranges) noexcept
Create an iterable view limited to given entity ranges.
Components Component types to fetch; first drives iteration order. ranges Half-open entity ranges. ArraysView instance (ranged iteration).
ecss::Registry< ThreadSafe, Allocator >::~Registry() noexcept
Destroys all component arrays (each SectorsArray is deleted).
void ecss::Registry< ThreadSafe, Allocator >::destroySector(EntityId entityId) noexcept
Destroy a single entity across all arrays (internal helper).
entityId Entity id.
void ecss::Registry< ThreadSafe, Allocator >::withPinned(EntityId entity, F &&f) noexcept
Utility: pin multiple components and invoke f(entity, comps...).
Ts Component types to pin. F Functor type.
static Memory::PinnedSector ecss::Registry< ThreadSafe, Allocator >::pinSector(SectorId pinId, const ArraysArr &arrays, Memory::SectorsArray< ThreadSafe, Allocator > *lockedArr, size_t index)
Internal helper: pin a sector from one of several arrays (thread-safe build).
T Component type stored in the pinned sector. ArraysArr Array-like container of SectorsArray*. pinId Sector id to pin. arrays Container of sectors arrays to search. lockedArr If not null, this array is already write-locked (skip locking). index Index in arrays to pin from. PinnedSector handle (may be empty if sector not found).
static void ecss::Registry< ThreadSafe, Allocator >::prepareEntities(std::vector< EntityId > &entities, size_t sectorsCapacity)
Internal helper: ensure entities vector is sorted & clamped to valid capacity.
entities [in/out] Vector of entity ids. sectorsCapacity Max valid sector index (exclusive).