ecss::Memory::SectorsArray
Iterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::begin() const
Iterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::end() const
IteratorAlive ecss::Memory::SectorsArray< ThreadSafe, Allocator >::beginAlive() const
IteratorAlive ecss::Memory::SectorsArray< ThreadSafe, Allocator >::beginAlive(const Ranges< SectorId > &ranges) const
IteratorAlive ecss::Memory::SectorsArray< ThreadSafe, Allocator >::endAlive() const
RangedIterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::beginRanged(const Ranges< SectorId > &ranges) const
RangedIterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::endRanged() const
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::findRightNearestSectorIndex(SectorId sectorId) const
Find the first linear index whose sector id >= sectorId.
Linear index or size() if none.
bool ecss::Memory::SectorsArray< ThreadSafe, Allocator >::containsSector(SectorId id) const
Sector * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::at(size_t sectorIndex) const
Sector * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::findSector(SectorId id) const
Sector * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getSector(SectorId id) const
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getSectorIndex(SectorId id) const
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getSectorIndex(Sector *sector) const
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::sectorsMapCapacity() const
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::capacity() const
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::size() const
bool ecss::Memory::SectorsArray< ThreadSafe, Allocator >::empty() const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::shrinkToFit()
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::reserve(uint32_t newCapacity)
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::clear()
auto ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getDefragmentationSize() const
auto ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getDefragmentationRatio() const
bool ecss::Memory::SectorsArray< ThreadSafe, Allocator >::needDefragment() const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::setDefragmentThreshold(float threshold)
Set ratio threshold (0..1) above which needDefragment()==true.
threshold Clamped into [0..1].
ShiftDirection
friend class ecss::ArraysView
friend class ecss::Registry
friend class SectorsArray
Allocator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mAllocator
Underlying memory & cursor provider.
uint32_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mDefragmentSize
Accumulated candidate size for defragmentation.
float ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mDefragThreshold
Ratio threshold for needDefragment().
std::vector<SectorId> ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mPendingErase
Deferred erase queue (ThreadSafe).
std::conditional_t<ThreadSafe, Threads::PinCounters, Dummy> ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mPinsCounter
Per-sector pin counters + global array lock state.
detail::SectorsMap<ThreadSafe> ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mSectorsMap
Id -> Sector* map (sparse).
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mSize
Linear alive+dead sector count (post-defrag shrinks).
std::conditional_t<ThreadSafe, std::shared_mutex, Dummy> ecss::Memory::SectorsArray< ThreadSafe, Allocator >::mtx
Container-level RW mutex (ThreadSafe builds).
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::defragment()
Defragment by collapsing dead (erased) sectors; preserves relative order of alive ones.
Blocks until all pins are released (ThreadSafe build).
T * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::emplace(SectorId sectorId, Args &&... args)
Construct in-place a member of type T.
T Component/member type. sectorId Sector id. args Constructor arguments. Pointer to newly constructed member.
Referenced by ecss::Memory::SectorsArray< ThreadSafe, Allocator >::push.
Iterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::erase(Iterator first, Iterator last, bool defragment=false) noexcept
Erase range [first, last).
first Begin iterator. last End iterator. defragment If true, compact storage after removal. Iterator at the starting position.
Iterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::erase(Iterator it, bool defragment=false) noexcept
Erase a single sector at iterator position.
it Iterator referencing the sector. defragment If true, compact storage afterwards. Iterator positioned at erased slot (or unchanged if invalid).
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::erase(size_t beginIdx, size_t count=1, bool defragment=false)
Erase sectors by linear index range (optionally defragment immediately).
beginIdx First index. count Number of sectors to erase (>=1). defragment If true, compacts immediately (costly). TS Allows skipping internal locking when false.
Referenced by ecss::Memory::SectorsArray< ThreadSafe, Allocator >::erase.
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::erase_if(Iterator first, Iterator last, Func &&func, bool defragment=false) noexcept
Conditionally erase sectors in [first,last), invoking predicate on each Sector*.
Func Predicate (Sector*) returning bool; if true sector is destroyed. first Begin iterator. last End iterator (half-open). func Predicate functor. defragment If true, triggers defragment at end (if something erased).
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::eraseAsync(SectorId id, size_t count=1)
Queue asynchronous erase by id (actual removal deferred).
id First sector id. count Number of consecutive ids to queue. Removal occurs in processPendingErases(); pinned sectors remain until unpinned.
FORCE_INLINE SectorLayoutMeta * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getLayout() const
The sector layout metadata used by this array.
Referenced by ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getLayoutData.
FORCE_INLINE const LayoutData & ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getLayoutData() const
Access per-type layout metadata (offset, alive mask, etc.).
Referenced by ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getLayoutData.
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::incDefragmentSize(uint32_t count=1)
Increment deferred defragment bytes counter.
std::remove_cvref_t< T > * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::insert(SectorId sectorId, T &&data)
Insert / overwrite a member (or whole Sector) at sectorId.
T Member type or Sector (for whole copy/move). sectorId Sector id (allocated if missing). data Source object (moved if rvalue). Pointer to inserted member (or sector pointer if T == Sector).
SectorsArray & ecss::Memory::SectorsArray< ThreadSafe, Allocator >::operator=(const SectorsArray &other)
SectorsArray & ecss::Memory::SectorsArray< ThreadSafe, Allocator >::operator=(const SectorsArray< T, Alloc > &other)
SectorsArray & ecss::Memory::SectorsArray< ThreadSafe, Allocator >::operator=(SectorsArray &&other) noexcept
SectorsArray & ecss::Memory::SectorsArray< ThreadSafe, Allocator >::operator=(SectorsArray< T, Alloc > &&other) noexcept
PinnedSector ecss::Memory::SectorsArray< ThreadSafe, Allocator >::pinBackSector() const
Pin last sector (by linear order).
TS If false, skip locking. Last sector pinned or empty if array empty.
PinnedSector ecss::Memory::SectorsArray< ThreadSafe, Allocator >::pinSector(Sector *sector) const
Pin a specific sector pointer (if not null).
TS If false, skip acquiring a shared lock (caller must ensure safety). sector Sector pointer (maybe null). PinnedSector (empty if sector==nullptr).
PinnedSector ecss::Memory::SectorsArray< ThreadSafe, Allocator >::pinSector(SectorId id) const
Pin sector by id if found.
TS If false, expect external synchronization. id Sector id. PinnedSector or empty if not present.
PinnedSector ecss::Memory::SectorsArray< ThreadSafe, Allocator >::pinSectorAt(size_t idx) const
Pin sector at a given linear index.
TS If false, skip locking. idx Linear index (0..size()). PinnedSector (empty if out-of-range).
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::processPendingErases(bool withDefragment=true)
Drain deferred erase queue and optionally defragment.
withDefragment If true and ratio above threshold, compacts after processing. Lock If true acquire internal lock (set false if caller already holds lock). Old retired buffers freed at end (ThreadSafe only).
T * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::push(SectorId sectorId, Args &&... args)
Convenience insertion: if single T argument => insert(); else emplace().
T Component/member type. sectorId Sector id. args Forwarded creation args.
ecss::Memory::SectorsArray< ThreadSafe, Allocator >::SectorsArray(const SectorsArray &other)
Same-type copy constructor.
ecss::Memory::SectorsArray< ThreadSafe, Allocator >::SectorsArray(const SectorsArray< T, Alloc > &other)
Cross-template copy constructor (allows copying between differently configured SectorsArray types if layout compatible).
T Other ThreadSafe flag. Alloc Other allocator type.
ecss::Memory::SectorsArray< ThreadSafe, Allocator >::SectorsArray(SectorsArray &&other) noexcept
Same-type move constructor.
ecss::Memory::SectorsArray< ThreadSafe, Allocator >::SectorsArray(SectorsArray< T, Alloc > &&other) noexcept
Cross-template move constructor.
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::tryDefragment()
Attempt a defragment only if array not logically pinned (non-blocking attempt).
ecss::Memory::SectorsArray< ThreadSafe, Allocator >::~SectorsArray()
Destructor clears all sectors and releases underlying memory.
Sector * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::acquireSectorImpl(SectorId sectorId)
FORCE_INLINE Sector * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::atImpl(size_t sectorIndex) const
FORCE_INLINE size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::capacityImpl() const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::clearImpl()
FORCE_INLINE bool ecss::Memory::SectorsArray< ThreadSafe, Allocator >::containsSectorImpl(SectorId id) const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::copy(const SectorsArray< T, Alloc > &other)
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::copyImpl(const SectorsArray< T, Alloc > &other)
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::defragmentImpl(size_t from=0)
Compact holes created by erased sectors starting from index from.
from Linear index to start scanning.
T * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::emplaceImpl(SectorId sectorId, Args &&... args)
FORCE_INLINE bool ecss::Memory::SectorsArray< ThreadSafe, Allocator >::emptyImpl() const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::erase_ifImpl(Iterator first, Iterator last, Func &&func, bool defragment=false) noexcept
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::eraseAsyncImpl(SectorId id)
Iterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::eraseImpl(Iterator first, Iterator last, bool defragment=false) noexcept
Iterator ecss::Memory::SectorsArray< ThreadSafe, Allocator >::eraseImpl(Iterator it, bool defragment=false) noexcept
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::findInsertPositionImpl(SectorId sectorId, size_t size) const
size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::findRightNearestSectorIndexImpl(SectorId sectorId) const
FORCE_INLINE Sector * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::findSectorImpl(SectorId id) const
FORCE_INLINE Sector * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getSectorImpl(SectorId id) const
FORCE_INLINE size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getSectorIndexImpl(Sector *sector) const
FORCE_INLINE size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::getSectorIndexImpl(SectorId id) const
std::remove_reference_t< T > * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::insertImpl(SectorId sectorId, T &&data)
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::move(SectorsArray< T, Alloc > &&other)
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::moveImpl(SectorsArray< T, Alloc > &&other)
PinnedSector ecss::Memory::SectorsArray< ThreadSafe, Allocator >::pinSectorImpl(Sector *sector) const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::processPendingErasesImpl(bool withDefragment=true)
auto ecss::Memory::SectorsArray< ThreadSafe, Allocator >::readLock() const
Shared read lock if ThreadSafe, otherwise a dummy object.
auto ecss::Memory::SectorsArray< ThreadSafe, Allocator >::readLock() const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::reserveImpl(uint32_t newCapacity)
ecss::Memory::SectorsArray< ThreadSafe, Allocator >::SectorsArray(SectorLayoutMeta *meta, Allocator &&allocator={})
Internal ctor with provided layout metadata + allocator.
meta Precomputed layout meta (SectorLayoutMeta owns offsets & liveness masks). allocator Allocator instance.
FORCE_INLINE size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::sectorsMapCapacityImpl() const
void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::shiftSectorsImpl(size_t from, size_t count=1)
Shift sectors left or right to open/close gaps.
ShiftDir Direction (Left / Right). from Starting linear index where shift begins. count How many slots to open/close.
FORCE_INLINE void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::shrinkToFitImpl()
FORCE_INLINE size_t ecss::Memory::SectorsArray< ThreadSafe, Allocator >::sizeImpl() const
auto ecss::Memory::SectorsArray< ThreadSafe, Allocator >::writeLock() const
Unique write lock if ThreadSafe, otherwise a dummy object.
auto ecss::Memory::SectorsArray< ThreadSafe, Allocator >::writeLock() const
static SectorsArray * ecss::Memory::SectorsArray< ThreadSafe, Allocator >::create(Allocator &&allocator={})
Factory to allocate a SectorsArray for the unique component type set Types.
Types Component types grouped in each sector (must be unique). allocator Allocator instance to move in. Newly allocated heap object (caller owns via delete).
static consteval void ecss::Memory::SectorsArray< ThreadSafe, Allocator >::enforceTSMode()