ecss::Memory::Sector
T * ecss::Memory::Sector::copyMember(const T &from, std::byte *toData, uint32_t &toIsAlive, const LayoutData &layout)
Copy-assign member T into destination and mark alive.
T Component type TS If true, uses atomic store for race-free lockless reads.
References destroyMember, getMemberPtr, setAlive.
void * ecss::Memory::Sector::copyMember(const void *from, std::byte *toData, uint32_t &toIsAlive, const LayoutData &layout)
Copy-assign an opaque member using layout function table.
ThreadSafe If true, uses atomic store for race-free lockless reads.
References destroyMember, getMemberPtr, setAlive.
void ecss::Memory::Sector::copySectorData(const std::byte *fromData, uint32_t fromIsAlive, std::byte *toData, uint32_t &toIsAlive, const SectorLayoutMeta *layouts)
Copy sector data from one location to another.
ThreadSafe If true, uses atomic store for race-free lockless reads. fromData Source sector data fromIsAlive Source alive state toData Destination sector data toIsAlive Reference to destination alive state (will be modified) layouts Sector layout metadata
References destroySectorData, getMemberPtr, isAlive.
void ecss::Memory::Sector::destroyMember(std::byte *data, uint32_t &isAliveData, const LayoutData &layout)
Destroy a specific member if alive and clear its liveness bits.
ThreadSafe If true, uses atomic store for race-free lockless reads.
References getMemberPtr, isAlive, setAlive.
Referenced by copyMember, copyMember, ecss::Registry< ThreadSafe, Allocator >::destroyComponent, ecss::Registry< ThreadSafe, Allocator >::destroyComponent, moveMember, moveMember.
void ecss::Memory::Sector::destroySectorData(std::byte *data, uint32_t &isAliveData, const SectorLayoutMeta *layouts)
Destroy all alive members in sector data and clear liveness bits.
ThreadSafe If true, uses atomic store for race-free lockless reads.
References getMemberPtr, isAlive, isSectorAlive.
Referenced by copySectorData, ecss::Registry< ThreadSafe, Allocator >::destroyEntities, moveSectorData.
T * ecss::Memory::Sector::emplaceMember(std::byte *data, uint32_t &isAliveData, const LayoutData &layout, Args &&... args)
(Re)construct member T in place and mark it alive. Destroys previous value if present.
T Component type TS If true, uses atomic store for race-free lockless reads. data Raw pointer to sector data isAliveData Reference to alive data (will be modified) layout Layout data for this component type args Constructor arguments Pointer to constructed component
References getMemberPtr, isAlive.
const T * ecss::Memory::Sector::getComponent(const std::byte *data, uint32_t isAliveData, SectorLayoutMeta *sectorLayout)
Fetch component pointer of type T using layout; may be nullptr if not alive.
References getMember.
Referenced by ecss::Registry< ThreadSafe, Allocator >::pinComponent.
T * ecss::Memory::Sector::getComponent(std::byte *data, uint32_t isAliveData, SectorLayoutMeta *sectorLayout)
FORCE_INLINE const T * ecss::Memory::Sector::getMember(const std::byte *data, const LayoutData &layout, uint32_t isAliveData) noexcept
FORCE_INLINE const T * ecss::Memory::Sector::getMember(const std::byte *data, uint16_t offset, uint32_t mask, uint32_t isAliveData) noexcept
FORCE_INLINE T * ecss::Memory::Sector::getMember(std::byte *data, const LayoutData &layout, uint32_t isAliveData) noexcept
Get a member pointer using layout metadata; returns nullptr if not alive.
References getMember.
FORCE_INLINE T * ecss::Memory::Sector::getMember(std::byte *data, uint16_t offset, uint32_t mask, uint32_t isAliveData) noexcept
Get a member pointer by offset if the corresponding liveness bit is set.
data Raw pointer to sector data offset Byte offset of the component mask Liveness bitmask for this component type isAliveData Current alive state from external array Pointer to T or nullptr if not alive.
Referenced by getComponent, getMember.
FORCE_INLINE const void * ecss::Memory::Sector::getMemberPtr(const std::byte *data, uint16_t offset) noexcept
FORCE_INLINE void * ecss::Memory::Sector::getMemberPtr(std::byte *data, uint16_t offset) noexcept
Raw member address by byte offset from the sector data base.
Referenced by copyMember, copyMember, copySectorData, destroyMember, destroySectorData, emplaceMember, moveMember, moveMember, moveSectorData.
FORCE_INLINE bool ecss::Memory::Sector::isAlive(uint32_t isAliveData, uint32_t mask) noexcept
Check whether any masked bit is marked alive.
Referenced by copySectorData, destroyMember, destroySectorData, emplaceMember, ecss::Registry< ThreadSafe, Allocator >::hasComponent, moveSectorData.
FORCE_INLINE bool ecss::Memory::Sector::isSectorAlive(uint32_t isAliveData) noexcept
Check whether any bit is marked alive (sector has any live component).
Referenced by destroySectorData.
FORCE_INLINE void ecss::Memory::Sector::markAlive(uint32_t &isAliveData, uint32_t mask) noexcept
FORCE_INLINE void ecss::Memory::Sector::markNotAlive(uint32_t &isAliveData, uint32_t mask) noexcept
T * ecss::Memory::Sector::moveMember(T &&from, std::byte *toData, uint32_t &toIsAlive, const LayoutData &layout)
Move-assign member T into destination and mark alive.
T Component type TS If true, uses atomic store for race-free lockless reads.
References destroyMember, getMemberPtr, setAlive.
void * ecss::Memory::Sector::moveMember(void *from, std::byte *toData, uint32_t &toIsAlive, const LayoutData &layout)
Move-assign an opaque member using layout function table.
ThreadSafe If true, uses atomic store for race-free lockless reads.
References destroyMember, getMemberPtr, setAlive.
void ecss::Memory::Sector::moveSectorData(std::byte *fromData, uint32_t &fromIsAlive, std::byte *toData, uint32_t &toIsAlive, const SectorLayoutMeta *layouts)
Move sector data from one location to another.
ThreadSafe If true, uses atomic store for race-free lockless reads. fromData Source sector data fromIsAlive Reference to source alive state (will be cleared) toData Destination sector data toIsAlive Reference to destination alive state (will be modified) layouts Sector layout metadata
References destroySectorData, getMemberPtr, isAlive.
FORCE_INLINE void ecss::Memory::Sector::setAlive(uint32_t &isAliveData, uint32_t mask, bool value) noexcept
Set or clear bits in isAliveData.
ThreadSafe If true, uses atomic store for race-free lockless reads. isAliveData Reference to alive data to modify mask Bitmask of bits to modify value If true, sets the bits; if false, clears them When value == false, mask should already be ~mask
Referenced by copyMember, copyMember, destroyMember, moveMember, moveMember.