ecss::Memory::Sector
SectorId ecss::Memory::Sector::id
uint32_t ecss::Memory::Sector::isAliveData
void ecss::Memory::Sector::destroyMember(const LayoutData &layout)
Destroy a specific member if alive and clear its liveness bits.
References getMemberPtr, isAlive, setAlive.
Referenced by copyMember, copyMember, moveMember, moveMember.
T * ecss::Memory::Sector::emplaceMember(const LayoutData &layout, Args &&... args)
(Re)construct member T in place and mark it alive. Destroys previous value if present.
References getMemberPtr, isAlive, markAlive.
FORCE_INLINE constexpr T * ecss::Memory::Sector::getMember(const LayoutData &layout)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References getMember.
FORCE_INLINE constexpr T * ecss::Memory::Sector::getMember(const LayoutData &layout) const
Get a member pointer using layout metadata; returns nullptr if not alive.
References getMember.
FORCE_INLINE constexpr T * ecss::Memory::Sector::getMember(uint16_t offset, uint32_t mask)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References getMemberPtr.
FORCE_INLINE constexpr T * ecss::Memory::Sector::getMember(uint16_t offset, uint32_t mask) const
Get a member pointer by offset if the corresponding liveness bit is set.
Pointer to T or nullptr if not alive.
References getMemberPtr.
Referenced by getComponentFromSector, getComponentFromSector, getMember, getMember.
FORCE_INLINE constexpr bool ecss::Memory::Sector::isAlive(size_t mask) const
Check whether any masked bit is marked alive.
mask Bitmask to test against isAliveData. true if any of the masked bits are set; otherwise, false.
Referenced by copySector, destroyMember, destroySector, emplaceMember, emplaceMember, moveSector.
FORCE_INLINE constexpr bool ecss::Memory::Sector::isSectorAlive() const
Check whether any bit is marked alive.
true if any of the bits are set; otherwise, false.
Referenced by destroySector.
FORCE_INLINE constexpr void ecss::Memory::Sector::markAlive(size_t mask)
Branch-free convenience for marking bits as alive (sets them to 1).
mask Bitmask of bits to set in isAliveData.
Referenced by emplaceMember, emplaceMember.
FORCE_INLINE constexpr void ecss::Memory::Sector::markNotAlive(size_t mask)
Branch-free convenience for marking bits as not alive (clears them to 0).
mask Bitmask of bits to clear in isAliveData.
FORCE_INLINE constexpr void ecss::Memory::Sector::setAlive(size_t mask, bool value)
Set or clear bits in isAliveData.
mask Bitmask of bits to modify (1s mark the affected bits). value If true, sets the bits in mask; if false, clears them. expected that if value == false - mask is already ~mask
Referenced by copyMember, copyMember, destroyMember, moveMember, moveMember, moveSector.
static T * ecss::Memory::Sector::copyMember(const T &from, Sector *to, const LayoutData &layout)
Copy-assign member T into to (replaces existing value) and mark alive.
References destroyMember, getMemberPtr, setAlive.
static void * ecss::Memory::Sector::copyMember(const void *from, Sector *to, const LayoutData &layout)
Copy-assign an opaque member using layout function table; marks alive if from is non-null.
References destroyMember, getMemberPtr, setAlive.
static Sector * ecss::Memory::Sector::copySector(Sector *from, Sector *to, const SectorLayoutMeta *layouts)
Copy-assign a sector using layout function table.
References destroySector, getMemberPtr, isAlive.
static void ecss::Memory::Sector::destroySector(Sector *sector, const SectorLayoutMeta *layouts)
Destroy all alive members in the sector using layout metadata and clear liveness bits.
References getMemberPtr, isAlive, isSectorAlive.
Referenced by copySector, ecss::Registry< ThreadSafe, Allocator >::destroyEntities, moveSector.
static T * ecss::Memory::Sector::emplaceMember(Sector *sector, const LayoutData &layout, Args &&... args)
Static helper: emplace member into a given sector.
References getMemberPtr, isAlive, markAlive.
static const T * ecss::Memory::Sector::getComponentFromSector(const Sector *sector, SectorLayoutMeta *sectorLayout)
Fetch component pointer of type T from a sector using its layout; may be nullptr if not alive.
References getMember.
Referenced by ecss::Registry< ThreadSafe, Allocator >::pinComponent.
static T * ecss::Memory::Sector::getComponentFromSector(Sector *sector, SectorLayoutMeta *sectorLayout)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References getMember.
static FORCE_INLINE void * ecss::Memory::Sector::getMemberPtr(const Sector *sectorAdr, uint16_t offset)
Raw member address by byte offset from the sector base.
Referenced by copyMember, copyMember, copySector, destroyMember, destroySector, emplaceMember, emplaceMember, getMember, getMember, moveMember, moveMember, moveSector.
static FORCE_INLINE void * ecss::Memory::Sector::getMemberPtr(Sector *sectorAdr, uint16_t offset)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
static FORCE_INLINE void * ecss::Memory::Sector::getMemberPtr(std::byte *sectorAdr, uint16_t offset)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
static T * ecss::Memory::Sector::moveMember(T &&from, Sector *to, const LayoutData &layout)
Move-assign member T into to (replaces existing value) and mark alive.
References destroyMember, getMemberPtr, setAlive.
static void * ecss::Memory::Sector::moveMember(void *from, Sector *to, const LayoutData &layout)
Move-assign an opaque member using layout function table; marks alive if from is non-null.
References destroyMember, getMemberPtr, setAlive.
static Sector * ecss::Memory::Sector::moveSector(Sector *from, Sector *to, const SectorLayoutMeta *layouts)
Move-assign a sector using layout function table.
References destroySector, getMemberPtr, isAlive, setAlive.