name: Docs (MkDocs + Doxygen → GitHub Pages)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'ecss/**'
      - '.github/workflows/docs.yml'

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip-ci]') == false
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen (latest)
        run: |
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_14_0/doxygen-1.14.0.linux.bin.tar.gz
          tar -xvzf doxygen-1.14.0.linux.bin.tar.gz
          sudo cp doxygen-1.14.0/bin/doxygen /usr/local/bin/doxygen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/.python/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
              
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/.python/requirements.txt

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
